# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:
  
  # This starts a local mongo DB.
  neo4j:
    container_name: neo4j
    networks:
      - shared-network
    image: neo4j
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    environment:
      NEO4J_AUTH: "none"

  # This is the core FRIENDS based service.
  friends:
    container_name: friends
    networks:
      - shared-network
    image: friends-amd64
    ports:
      - 3000:3000 # friends API
      - 4000:4000 # DEBUG API
    links:
      - "neo4j:db"
    # environment:
      # - FRIENDS_DB_HOST=docker.for.mac.localhost:7687
      # - GODEBUG=gctrace=1

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: metrics-amd64
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  # This sidecar publishes tracing to the console by default.
  tracer:
    container_name: tracer
    networks:
      - shared-network
    image: tracer-amd64
    ports:
      - 3002:3002 # TRACER API
      - 4002:4002 # DEBUG API
    # environment:
      # - FRIENDS_ZIPKIN_HOST=http://zipkin:9411/api/v2/spans
  
  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin
    ports:
      - 9411:9411
